all: main.out

quadraticRoots.o: quadraticRoots.h quadraticRoots.c
	gcc -c quadraticRoots.c -o quadraticRoots.o

main.out: quadraticRoots.o main.c
	gcc quadraticRoots.o main.c -lm -o main.out

clear:
	rm -f *.o *.out