all:taskmanager.out

taskmanager.out:processes.o taskmanager.c
  gcc taskmanager.c processes.o -o taskmanager.out

processes.o:processes.c processes.h
  gcc -c processes.c -o processes.o

clear:
  rm -f *.o *.out